### ISSUE TITLE
Plugin.js missing

### ISSUE THREAD

**Issue by Ra-is** [adeslade/imageupload#1]
Am using your plugin in tinymce4 but am it seems tinymce is looking for plugin.min.js in your file

**Comment by emslade** [comment]
Hi @Ra-is, I haven't touched this repository for quite some time I'm afraid. I'm no longer maintaining it and have updated the README with that information.

Perhaps https://github.com/boxuk/tinymce-imageupload would be better for you? It supports TinyMCE apparently.

Cheers
